INSERT INTO Teams (team_id, team_name, city, stadium, founded_year, manager) VALUES
(42, 'Arsenal', 'London', 'Emirates Stadium', 1886, 'Mikel Arteta'),
(31, 'Leicester City', 'Leicester', 'King Power Stadium', 1884, 'Steve Cooper'),
(30, 'Brighton & Hove Albion', 'Brighton', 'Amex Stadium', 1901, 'Fabian Hürzeler'),
(50, 'Brentford', 'London', 'Gtech Community Stadium', 1889, 'Thomas Frank'),
(60, 'Bournemouth', 'Bournemouth', 'Vitality Stadium', 1899, 'Andoni Iraola'),
(40, 'Aston Villa', 'Birmingham', 'Villa Park', 1874, 'Unai Emery'),
(14, 'Nottingham Forest', 'Nottingham', 'City Ground', 1865, 'Nuno Espírito Santo'),
(3, 'Wolverhampton Wanderers', 'Wolverhampton', 'Molineux Stadium', 1877, 'Gary O''Neil'),
(43, 'Fulham', 'London', 'Craven Cottage', 1879, 'Marco Silva'),
(17, 'Manchester City', 'Manchester', 'Etihad Stadium', 1880, 'Pep Guardiola'),
(37, 'West Ham United', 'London', 'London Stadium', 1895, 'Julen Lopetegui'),
(32, 'Ipswich Town', 'Ipswich', 'Portman Road', 1878, 'Kieran McKenna'),
(33, 'Tottenham Hotspur', 'London', 'Tottenham Hotspur Stadium', 1882, 'Ange Postecoglou'),
(7, 'Crystal Palace', 'London', 'Selhurst Park', 1905, 'Oliver Glasner'),
(35, 'Manchester United', 'Manchester', 'Old Trafford', 1878, 'Rúben Amorim'),
(45, 'Southampton', 'Southampton', 'St Mary''s Stadium', 1885, 'Russell Martin'),
(38, 'Chelsea', 'London', 'Stamford Bridge', 1905, 'Enzo Maresca'),
(48, 'Everton', 'Liverpool', 'Goodison Park', 1878, 'Sean Dyche'),
(39, 'Newcastle United', 'Newcastle upon Tyne', 'St James'' Park', 1892, 'Eddie Howe'),
(44, 'Liverpool', 'Liverpool', 'Anfield', 1892, 'Arne Slot');
